// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DAL;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20250306083350_Start_data")]
    partial class Start_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Desc = "Explosive scenes, high energy, and intense stunts.",
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            Desc = "Designed to make the audience laugh.",
                            Name = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Desc = "Focuses on emotional and relational development.",
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Desc = "Intended to scare and create suspense.",
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            Desc = "Futuristic themes, advanced technology, and space travel.",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 6,
                            Desc = "Magical worlds, mythical creatures, and epic adventures.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 7,
                            Desc = "Exciting and suspenseful, often involving crime or espionage.",
                            Name = "Thriller"
                        },
                        new
                        {
                            CategoryId = 8,
                            Desc = "Factual storytelling and real-life events.",
                            Name = "Documentary"
                        },
                        new
                        {
                            CategoryId = 9,
                            Desc = "Love stories with emotional connections.",
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryId = 10,
                            Desc = "Movies created with animated characters and stories.",
                            Name = "Animation"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 1,
                            Desc = "Post-apocalyptic action-packed film.",
                            Director = "George Miller",
                            Price = 19.99m,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 2,
                            Desc = "Comedy about a bachelor party gone wrong.",
                            Director = "Todd Phillips",
                            Price = 14.99m,
                            Title = "The Hangover"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 3,
                            Desc = "Classic mafia drama.",
                            Director = "Francis Ford Coppola",
                            Price = 24.99m,
                            Title = "The Godfather"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 4,
                            Desc = "Horror based on real paranormal investigations.",
                            Director = "James Wan",
                            Price = 12.99m,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 5,
                            Desc = "A sci-fi adventure through space and time.",
                            Director = "Christopher Nolan",
                            Price = 22.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 6,
                            Desc = "Fantasy adventure about a young wizard.",
                            Director = "Chris Columbus",
                            Price = 18.99m,
                            Title = "Harry Potter and the Sorcerer’s Stone"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 7,
                            Desc = "A thriller about dreams within dreams.",
                            Director = "Christopher Nolan",
                            Price = 21.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 8,
                            Desc = "Stunning nature documentary.",
                            Director = "Alastair Fothergill",
                            Price = 29.99m,
                            Title = "Planet Earth"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 9,
                            Desc = "Epic romance set on the ill-fated ship.",
                            Director = "James Cameron",
                            Price = 19.99m,
                            Title = "Titanic"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 10,
                            Desc = "Classic animated film about talking toys.",
                            Director = "John Lasseter",
                            Price = 14.99m,
                            Title = "Toy Story"
                        },
                        new
                        {
                            FilmId = 11,
                            CategoryId = 1,
                            Desc = "Action film set in a high-rise building.",
                            Director = "John McTiernan",
                            Price = 17.99m,
                            Title = "Die Hard"
                        },
                        new
                        {
                            FilmId = 12,
                            CategoryId = 2,
                            Desc = "Teen comedy about friendship.",
                            Director = "Greg Mottola",
                            Price = 13.99m,
                            Title = "Superbad"
                        },
                        new
                        {
                            FilmId = 13,
                            CategoryId = 3,
                            Desc = "Drama about a man’s extraordinary life journey.",
                            Director = "Robert Zemeckis",
                            Price = 16.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            FilmId = 14,
                            CategoryId = 4,
                            Desc = "Horror classic featuring Freddy Krueger.",
                            Director = "Wes Craven",
                            Price = 10.99m,
                            Title = "A Nightmare on Elm Street"
                        },
                        new
                        {
                            FilmId = 15,
                            CategoryId = 5,
                            Desc = "Sci-fi neo-noir about artificial intelligence.",
                            Director = "Denis Villeneuve",
                            Price = 23.99m,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            FilmId = 16,
                            CategoryId = 6,
                            Desc = "Fantasy epic set in Middle-earth.",
                            Director = "Peter Jackson",
                            Price = 25.99m,
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            FilmId = 17,
                            CategoryId = 7,
                            Desc = "Thriller about a serial killer.",
                            Director = "David Fincher",
                            Price = 20.99m,
                            Title = "Se7en"
                        },
                        new
                        {
                            FilmId = 18,
                            CategoryId = 8,
                            Desc = "True crime documentary series.",
                            Director = "Moira Demos",
                            Price = 27.99m,
                            Title = "Making a Murderer"
                        },
                        new
                        {
                            FilmId = 19,
                            CategoryId = 9,
                            Desc = "Romantic drama based on Nicholas Sparks’ novel.",
                            Director = "Nick Cassavetes",
                            Price = 15.99m,
                            Title = "The Notebook"
                        },
                        new
                        {
                            FilmId = 20,
                            CategoryId = 10,
                            Desc = "Animated adventure about an ogre’s journey.",
                            Director = "Andrew Adamson",
                            Price = 14.49m,
                            Title = "Shrek"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Film", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
