// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DAL;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20250306094657_Start_data_moze_zadziala")]
    partial class Start_data_moze_zadziala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Desc = "Filmy pełne dynamicznych scen i efektów specjalnych.",
                            Name = "Akcja"
                        },
                        new
                        {
                            CategoryId = 2,
                            Desc = "Filmy zapewniające rozrywkę i humor.",
                            Name = "Komedia"
                        },
                        new
                        {
                            CategoryId = 3,
                            Desc = "Filmy o głębokich emocjach i poważnych tematach.",
                            Name = "Dramat"
                        },
                        new
                        {
                            CategoryId = 4,
                            Desc = "Filmy, które wywołują strach i napięcie.",
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            Desc = "Filmy opowiadające o futurystycznych technologiach i kosmosie.",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            CategoryId = 6,
                            Desc = "Filmy pełne magii i niezwykłych światów.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 7,
                            Desc = "Filmy trzymające w napięciu z nieoczekiwanymi zwrotami akcji.",
                            Name = "Thriller"
                        },
                        new
                        {
                            CategoryId = 8,
                            Desc = "Filmy animowane, często dla dzieci i rodzin.",
                            Name = "Animacja"
                        },
                        new
                        {
                            CategoryId = 9,
                            Desc = "Filmy oparte na faktach i rzeczywistych wydarzeniach.",
                            Name = "Dokumentalny"
                        },
                        new
                        {
                            CategoryId = 10,
                            Desc = "Filmy o miłości i relacjach międzyludzkich.",
                            Name = "Romans"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 1,
                            Desc = "Postapokaliptyczna walka o przetrwanie.",
                            Director = "George Miller",
                            Price = 29.99m,
                            Title = "Mad Max: Na drodze gniewu"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 1,
                            Desc = "Historia rzymskiego generała, który staje się gladiatorem.",
                            Director = "Ridley Scott",
                            Price = 34.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 2,
                            Desc = "Bohater z ciętym językiem i niezwykłymi umiejętnościami.",
                            Director = "Tim Miller",
                            Price = 24.99m,
                            Title = "Deadpool"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 3,
                            Desc = "Historia człowieka, który przypadkiem wpływa na historię świata.",
                            Director = "Robert Zemeckis",
                            Price = 19.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 4,
                            Desc = "Załoga statku kosmicznego walczy z obcym stworzeniem.",
                            Director = "Ridley Scott",
                            Price = 39.99m,
                            Title = "Obcy: Ósmy pasażer Nostromo"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 5,
                            Desc = "Rzeczywistość to iluzja kontrolowana przez maszyny.",
                            Director = "Lana i Lilly Wachowski",
                            Price = 29.99m,
                            Title = "Matrix"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 6,
                            Desc = "Podróż Froda i jego towarzyszy w celu zniszczenia pierścienia.",
                            Director = "Peter Jackson",
                            Price = 49.99m,
                            Title = "Władca Pierścieni: Drużyna Pierścienia"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 7,
                            Desc = "Złodziej kradnie sekrety z umysłów podczas snu.",
                            Director = "Christopher Nolan",
                            Price = 34.99m,
                            Title = "Incepcja"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 8,
                            Desc = "Ogr wyrusza na misję, by odzyskać swoje bagno.",
                            Director = "Andrew Adamson, Vicky Jenson",
                            Price = 14.99m,
                            Title = "Shrek"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 9,
                            Desc = "Dokument ukazujący piękno naszej planety.",
                            Director = "Richard Dale",
                            Price = 24.99m,
                            Title = "Ziemia: Niezwykły dzień"
                        },
                        new
                        {
                            FilmId = 11,
                            CategoryId = 10,
                            Desc = "Historia miłości na pokładzie słynnego statku.",
                            Director = "James Cameron",
                            Price = 19.99m,
                            Title = "Titanic"
                        },
                        new
                        {
                            FilmId = 12,
                            CategoryId = 1,
                            Desc = "Zabójca wraca do gry, by pomścić stratę.",
                            Director = "Chad Stahelski",
                            Price = 29.99m,
                            Title = "John Wick"
                        },
                        new
                        {
                            FilmId = 13,
                            CategoryId = 2,
                            Desc = "Dwoje przyjaciół próbuje przeżyć zwariowaną noc.",
                            Director = "Greg Mottola",
                            Price = 19.99m,
                            Title = "Superbad"
                        },
                        new
                        {
                            FilmId = 14,
                            CategoryId = 4,
                            Desc = "Rodzina ukrywa się przed potworami reagującymi na dźwięk.",
                            Director = "John Krasinski",
                            Price = 27.99m,
                            Title = "Ciche miejsce"
                        },
                        new
                        {
                            FilmId = 15,
                            CategoryId = 5,
                            Desc = "Misja kosmiczna w poszukiwaniu nowego domu dla ludzkości.",
                            Director = "Christopher Nolan",
                            Price = 39.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            FilmId = 16,
                            CategoryId = 6,
                            Desc = "Młody czarodziej odkrywa swoje przeznaczenie.",
                            Director = "Chris Columbus",
                            Price = 29.99m,
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            FilmId = 17,
                            CategoryId = 3,
                            Desc = "Portret psychologiczny upadku człowieka.",
                            Director = "Todd Phillips",
                            Price = 31.99m,
                            Title = "Joker"
                        },
                        new
                        {
                            FilmId = 18,
                            CategoryId = 8,
                            Desc = "Zabawki ożywają, gdy ludzie ich nie widzą.",
                            Director = "John Lasseter",
                            Price = 19.99m,
                            Title = "Toy Story"
                        },
                        new
                        {
                            FilmId = 19,
                            CategoryId = 6,
                            Desc = "Opowieść o walce między naturą a cywilizacją.",
                            Director = "Hayao Miyazaki",
                            Price = 34.99m,
                            Title = "Księżniczka Mononoke"
                        },
                        new
                        {
                            FilmId = 20,
                            CategoryId = 1,
                            Desc = "Oddział wyrusza na misję ratunkową podczas II wojny światowej.",
                            Director = "Steven Spielberg",
                            Price = 39.99m,
                            Title = "Szeregowiec Ryan"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Film", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
